var searchData=
[
  ['undoavailable',['undoAvailable',['https://doc.qt.io/qt-5/qlineedit.html#undoAvailable-prop',0,'QLineEdit']]],
  ['undolimit',['undoLimit',['https://doc.qt.io/qt-5/qundostack.html#undoLimit-prop',0,'QUndoStack']]],
  ['undoredoenabled',['undoRedoEnabled',['https://doc.qt.io/qt-5/qplaintextedit.html#undoRedoEnabled-prop',0,'QPlainTextEdit::undoRedoEnabled()'],['https://doc.qt.io/qt-5/qtextbrowser.html#undoRedoEnabled-prop',0,'QTextBrowser::undoRedoEnabled()'],['https://doc.qt.io/qt-5/qtextedit.html#undoRedoEnabled-prop',0,'QTextEdit::undoRedoEnabled()'],['https://doc.qt.io/qt-5/qtextdocument.html#undoRedoEnabled-prop',0,'QTextDocument::undoRedoEnabled()']]],
  ['unifiedtitleandtoolbaronmac',['unifiedTitleAndToolBarOnMac',['https://doc.qt.io/qt-5/qmainwindow.html#unifiedTitleAndToolBarOnMac-prop',0,'QMainWindow']]],
  ['uniformitemsizes',['uniformItemSizes',['https://doc.qt.io/qt-5/qlistview.html#uniformItemSizes-prop',0,'QListView']]],
  ['uniformrowheights',['uniformRowHeights',['https://doc.qt.io/qt-5/qtreeview.html#uniformRowHeights-prop',0,'QTreeView']]],
  ['updateinterval',['updateInterval',['https://doc.qt.io/qt-5/qgeopositioninfosource.html#updateInterval-prop',0,'QGeoPositionInfoSource::updateInterval()'],['https://doc.qt.io/qt-5/qgeosatelliteinfosource.html#updateInterval-prop',0,'QGeoSatelliteInfoSource::updateInterval()'],['https://doc.qt.io/qt-5/qtimeline.html#updateInterval-prop',0,'QTimeLine::updateInterval()']]],
  ['updatesenabled',['updatesEnabled',['https://doc.qt.io/qt-5/qwidget.html#updatesEnabled-prop',0,'QWidget']]],
  ['upvector',['upVector',['https://doc.qt.io/qt-5/qt3drender-qcamera.html#upVector-prop',0,'Qt3DRender::QCamera']]],
  ['url',['url',['https://doc.qt.io/qt-5/qqmlcomponent.html#url-prop',0,'QQmlComponent::url()'],['https://doc.qt.io/qt-5/qwebenginepage.html#url-prop',0,'QWebEnginePage::url()'],['https://doc.qt.io/qt-5/qwebengineview.html#url-prop',0,'QWebEngineView::url()'],['https://doc.qt.io/qt-5/qquickitemgrabresult.html#url-prop',0,'QQuickItemGrabResult::url()']]],
  ['usage',['usage',['https://doc.qt.io/qt-5/qt3drender-qbuffer.html#usage-prop',0,'Qt3DRender::QBuffer']]],
  ['usedesignmetrics',['useDesignMetrics',['https://doc.qt.io/qt-5/qtextdocument.html#useDesignMetrics-prop',0,'QTextDocument']]],
  ['usehovereffects',['useHoverEffects',['https://doc.qt.io/qt-5/qstylehints.html#useHoverEffects-prop',0,'QStyleHints']]],
  ['useragent',['userAgent',['https://doc.qt.io/qt-5/qabstractoauth2.html#userAgent-prop',0,'QAbstractOAuth2']]],
  ['userorientation',['userOrientation',['https://doc.qt.io/qt-5/qsensor.html#userOrientation-prop',0,'QSensor']]],
  ['userscripts',['userScripts',['https://doc.qt.io/qt-5/qquickwebengineprofile.html#userScripts-prop',0,'QQuickWebEngineProfile']]],
  ['usertlextensions',['useRtlExtensions',['https://doc.qt.io/qt-5/qstylehints.html#useRtlExtensions-prop',0,'QStyleHints']]],
  ['usesscrollbuttons',['usesScrollButtons',['https://doc.qt.io/qt-5/qtabbar.html#usesScrollButtons-prop',0,'QTabBar::usesScrollButtons()'],['https://doc.qt.io/qt-5/qtabwidget.html#usesScrollButtons-prop',0,'QTabWidget::usesScrollButtons()']]],
  ['uvw',['uvw',['https://doc.qt.io/qt-5/qt3drender-qpicktriangleevent.html#uvw-prop',0,'Qt3DRender::QPickTriangleEvent']]]
];
