var searchData=
[
  ['x',['x',['http://doc.qt.io/qt-5/qgraphicsobject.html#x-prop',0,'QGraphicsObject::x()'],['http://doc.qt.io/qt-5/qwidget.html#x-prop',0,'QWidget::x()'],['http://doc.qt.io/qt-5/qwindow.html#x-prop',0,'QWindow::x()'],['http://doc.qt.io/qt-5/qaccelerometerreading.html#x-prop',0,'QAccelerometerReading::x()'],['http://doc.qt.io/qt-5/qgyroscopereading.html#x-prop',0,'QGyroscopeReading::x()'],['http://doc.qt.io/qt-5/qmagnetometerreading.html#x-prop',0,'QMagnetometerReading::x()'],['http://doc.qt.io/qt-5/qrotationreading.html#x-prop',0,'QRotationReading::x()'],['http://doc.qt.io/qt-5/qquickitem.html#x-prop',0,'QQuickItem::x()'],['http://doc.qt.io/qt-5/qt3drender-qtexturewrapmode.html#x-prop',0,'Qt3DRender::QTextureWrapMode::x()'],['http://doc.qt.io/qt-5/qt3dinput-qmouseevent.html#x-prop',0,'Qt3DInput::QMouseEvent::x()'],['http://doc.qt.io/qt-5/qt3dinput-qwheelevent.html#x-prop',0,'Qt3DInput::QWheelEvent::x()']]],
  ['xextent',['xExtent',['http://doc.qt.io/qt-5/qt3dextras-qcuboidgeometry.html#xExtent-prop',0,'Qt3DExtras::QCuboidGeometry::xExtent()'],['http://doc.qt.io/qt-5/qt3dextras-qcuboidmesh.html#xExtent-prop',0,'Qt3DExtras::QCuboidMesh::xExtent()']]],
  ['xoffset',['xOffset',['http://doc.qt.io/qt-5/qgraphicsdropshadoweffect.html#xOffset-prop',0,'QGraphicsDropShadowEffect']]],
  ['xrotation',['xRotation',['http://doc.qt.io/qt-5/qtiltreading.html#xRotation-prop',0,'QTiltReading']]],
  ['xscale',['xScale',['http://doc.qt.io/qt-5/qgraphicsscale.html#xScale-prop',0,'QGraphicsScale']]],
  ['xymeshresolution',['xyMeshResolution',['http://doc.qt.io/qt-5/qt3dextras-qcuboidgeometry.html#xyMeshResolution-prop',0,'Qt3DExtras::QCuboidGeometry::xyMeshResolution()'],['http://doc.qt.io/qt-5/qt3dextras-qcuboidmesh.html#xyMeshResolution-prop',0,'Qt3DExtras::QCuboidMesh::xyMeshResolution()']]],
  ['xzmeshresolution',['xzMeshResolution',['http://doc.qt.io/qt-5/qt3dextras-qcuboidgeometry.html#xzMeshResolution-prop',0,'Qt3DExtras::QCuboidGeometry::xzMeshResolution()'],['http://doc.qt.io/qt-5/qt3dextras-qcuboidmesh.html#xzMeshResolution-prop',0,'Qt3DExtras::QCuboidMesh::xzMeshResolution()']]]
];
